apiVersion: v2
name: inkstone
description: Inkstone is a self-hosted reMarkable sync cloud (a maintained rmfakecloud fork) with native v6/Paper Pro PDF rendering, in case you want to sync/backup your files and have full control of the hosting/storage environment.
type: application
version: 0.2.0
appVersion: "0.0.9"
